In [ ]:
from google.colab import drive
import pandas as pd

# Monta Google Drive per salvare il file
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#import pandas as pd
#df = pd.read_csv("hf://datasets/joseagmz/MedQnA_version3/medDataset_processed.csv")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [ ]:
leggi df da output_path = '/content/drive/MyDrive/lavoro/Ricerca/CHI/df1csv_caring.csv'

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/lavoro/Ricerca/CHI/df1csv_caring.csv')

In [ ]:
df

,context,question,Answer_medico,Answer_LLM,Answer_LLM_PALMYRA,Sentiment_medico,Sentiment_LLM,Sentiment_LLM_PALMYRA,Answer_medico_concepts,Answer_LLM_concepts,...,Length_Answer_LLM_PALMYRA_prompt2,Answer_LLM_prompt2_FleschKincaid,Answer_LLM_prompt2_GunningFog,Answer_LLM_PALMYRA_prompt2_FleschKincaid,Answer_LLM_PALMYRA_prompt2_GunningFog,Answer_LLM_prompt2_emotions,Answer_LLM_PALMYRA_prompt2_emotions,Answer_medico_emotions,Answer_LLM_emotions,Answer_LLM_PALMYRA_emotions
0,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,LCMV infections can occur after exposure to fr...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Individuals who are at risk for Lymphocytic Ch...,Very Negative,Very Negative,Negative,LCMV exposure to fresh urine droppings saliva ...,Lymphocytic Choriomeningitis LCM viral infecti...,...,419,9.9,11.04,12.1,13.20,"{'neutral': np.float64(0.8154), 'approval': np...","{'neutral': np.float64(0.4486), 'caring': np.f...","{'neutral': np.float64(0.81), 'approval': np.f...","{'neutral': np.float64(0.557), 'approval': np....","{'neutral': np.float64(0.8582), 'approval': np..."
1,symptoms,What are the symptoms of Lymphocytic Choriomen...,LCMV is most commonly recognized as causing ne...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Negative,Neutral,Very Negative,LCMV neurological disease implies infection sy...,Lymphocytic Choriomeningitis LCM viral infecti...,...,585,11.5,12.40,10.6,13.48,"{'caring': np.float64(0.5921), 'approval': np....","{'neutral': np.float64(0.5146), 'confusion': n...","{'neutral': np.float64(0.8115), 'approval': np...","{'neutral': np.float64(0.3162), 'confusion': n...","{'neutral': np.float64(0.4024), 'approval': np..."
2,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,Individuals of all ages who come into contact ...,Individuals at risk for Lymphocytic Choriomeni...,Individuals who are at risk for Lymphocytic Ch...,Very Negative,Very Negative,Negative,Individuals ages contact with urine feces sali...,Individuals risk Lymphocytic Choriomeningitis ...,...,419,10.3,10.53,12.1,13.20,"{'neutral': np.float64(0.7154), 'approval': np...","{'neutral': np.float64(0.4486), 'caring': np.f...","{'neutral': np.float64(0.577), 'approval': np....","{'neutral': np.float64(0.5789), 'approval': np...","{'neutral': np.float64(0.8582), 'approval': np..."
3,exams and tests,How to diagnose Lymphocytic Choriomeningitis (...,"During the first phase of the disease, the mos...",Lymphocytic Choriomeningitis (LCM) is typicall...,To diagnose Lymphocytic Choriomeningitis (LCM)...,Negative,Neutral,Neutral,phase disease laboratory abnormalities white b...,Lymphocytic Choriomeningitis LCM diagnosed cli...,...,822,9.3,10.42,11.1,12.98,"{'neutral': np.float64(0.631), 'approval': np....","{'neutral': np.float64(0.4749), 'approval': np...","{'neutral': np.float64(0.9021), 'realization':...","{'neutral': np.float64(0.7318), 'approval': np...","{'neutral': np.float64(0.9108), 'approval': np..."
4,treatment,What are the treatments for Lymphocytic Chorio...,"Aseptic meningitis, encephalitis, or meningoen...",Lymphocytic Choriomeningitis (LCM) is a viral ...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Neutral,Neutral,Neutral,Aseptic meningitis encephalitis meningoencepha...,Lymphocytic Choriomeningitis LCM viral infecti...,...,683,11.8,13.48,12.4,14.23,"{'neutral': np.float64(0.3496), 'approval': np...","{'neutral': np.float64(0.3772), 'caring': np.f...","{'neutral': np.float64(0.7539), 'disapproval':...","{'neutral': np.float64(0.6613), 'caring': np.f...","{'neutral': np.float64(0.5117), 'approval': np..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16402,symptoms,What are the symptoms of Familial visceral myo...,What are the signs and symptoms of Familial vi...,Familial visceral myopathy with external ophth...,Familial visceral myopathy with external ophth...,Neutral,Very Negative,Very Negative,signs symptoms Familial visceral myopathy exte...,Familial visceral myopathy external ophthalmop...,...,712,14.5,15.41,14.5,15.41,"{'neutral': np.float64(0.3926), 'realization':...","{'neutral': np.float64(0.3926), 'realization':...","{'neutral': np.float64(0.8247), 'curiosity': n...","{'neutral': np.float64(0.8319), 'approval': np...","{'neutral': np.float64(0.8232), 'realization':..."
16403,information,What is (are) Pseudopelade of Brocq ?,Pseudopelade of Brocq (PBB) is a slowly progre...,Pseudopelade of Brocq is a rare type of scarri...,"Pseudopelade of Brocq is a rare, chronic, and ...",Neutral,Very Negative,Very Negative,Pseudopelade Brocq PBB progressive chronic con...,Pseudopelade Brocq scarring alopecia group con...,...,569,8.3,10.95,8.3,10.95,"{'neutral': np.float64(0.6931), 'confusion': n...","{'neutral': np.float64(0.6931), 'confusion': n...","{'confusion': np.float64(0.662), 'neutral': np...","{'neutral': np.float64(0.6695), 'realization':...","{'confusion': np.float64(0.3113), 'neutral': n..."
16404,symptoms,What are the symptoms of Pseudopelade of Brocq ?,What are the signs and symptoms of Pseudopelad...,"Pseudopelade of Brocq is a rare, chronic, and ...","Pseudopelade of Brocq is a rare, chronic, and ...",Neutral,Very Negative,Very Negative,signs symptoms Pseudopelade Brocq Human signs ...,Pseudopelade Brocq rare chronic progressive co...,...,564,9.3,11.34,9.3,11.34,"{'caring': np.float64(0.2741), 'neutral': np.f...","{'caring': np.float64(0.2741), 'neutral': np.f...","{'neutral': np.float64(0.8301), 'curiosity': n...","{'neutral': np.float64(0.7161), 'realization':...","{'neutral': np.float64(0.6501), 'sadness': np...."
16405,treatment,What are the treatments for Pseudopelade of Br...,Is there treatment or a cure for pseudopelade ...,"Pseudopelade of Brocq is a rare, chronic infla...","Pseudopelade of Brocq is a rare, chronic, and ...",Neutral,Neutral,Neutral,treatment cure pseudopelade Brocq effective tr...,Pseudopelade Brocq rare chronic inflammatory s...,...,570,11.2,12.74,11.2,12.74,"{'caring': np.float64(0.595), 'neutral': np.fl...","{'caring': np.float64(0.595), 'neutral': np.fl...","{'confusion': np.float64(0.2811), 'curiosity':...","{'neutral': np.float64(0.6682), 'approval': np...","{'neutral': np.float64(0.7205), 'approval': np..."
16406,information,What is (are) Desmoplastic small round cell tu...,"Desmoplastic small round cell tumors (DSRCT), ...",Desmoplastic small round cell tumor (DSRCT) is...,Desmoplastic small round cell tumor (DSRCT) is...,Very Negative,Neutral,Very Negative,Desmoplastic small round cell tumors DSRCT mal...,Desmoplastic small round cell tumor DSRCT mali...,...,441,10.6,12.85,10.6,12.85,"{'neutral': np.float64(0.832), 'approval': np....","{'neutral': np.float64(0.832), 'approval': np....","{'neutral': np.float64(0.9081), 'approval': np...","{'neutral': np.float64(0.6446), 'approval': np...","{'neutral': np.float64(0.7865), 'approval': np..."

In [ ]:
df3 = pd.read_csv("/content/drive/MyDrive/lavoro/Ricerca/CHI/df1csv.csv")

In [ ]:
df3

,context,question,Answer_medico,Answer_LLM,Answer_LLM_PALMYRA,Answer_LLM_PALMYRA_prompt2,Answer_LLM_prompt2
0,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,LCMV infections can occur after exposure to fr...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Individuals who are at risk for Lymphocytic Ch...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Lymphocytic Choriomeningitis (LCM) is a viral ...
1,symptoms,What are the symptoms of Lymphocytic Choriomen...,LCMV is most commonly recognized as causing ne...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Lymphocytic Choriomeningitis (LCM) is a viral ...,"Lymphocytic Choriomeningitis, or LCM, is a vir...",Lymphocytic Choriomeningitis (LCM) is a viral ...
2,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,Individuals of all ages who come into contact ...,Individuals at risk for Lymphocytic Choriomeni...,Individuals who are at risk for Lymphocytic Ch...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Lymphocytic Choriomeningitis (LCM) is a viral ...
3,exams and tests,How to diagnose Lymphocytic Choriomeningitis (...,"During the first phase of the disease, the mos...",Lymphocytic Choriomeningitis (LCM) is typicall...,To diagnose Lymphocytic Choriomeningitis (LCM)...,"To diagnose Lymphocytic Choriomeningitis, or L...",To diagnose Lymphocytic Choriomeningitis (LCM)...
4,treatment,What are the treatments for Lymphocytic Chorio...,"Aseptic meningitis, encephalitis, or meningoen...",Lymphocytic Choriomeningitis (LCM) is a viral ...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Lymphocytic Choriomeningitis (LCM) is a viral ...
...,...,...,...,...,...,...,...
16402,symptoms,What are the symptoms of Familial visceral myo...,What are the signs and symptoms of Familial vi...,Familial visceral myopathy with external ophth...,Familial visceral myopathy with external ophth...,Familial visceral myopathy with external ophth...,NaN
16403,information,What is (are) Pseudopelade of Brocq ?,Pseudopelade of Brocq (PBB) is a slowly progre...,Pseudopelade of Brocq is a rare type of scarri...,"Pseudopelade of Brocq is a rare, chronic, and ...",Pseudopelade of Brocq is a condition that affe...,NaN
16404,symptoms,What are the symptoms of Pseudopelade of Brocq ?,What are the signs and symptoms of Pseudopelad...,"Pseudopelade of Brocq is a rare, chronic, and ...","Pseudopelade of Brocq is a rare, chronic, and ...",Pseudopelade of Brocq is a rare condition that...,NaN
16405,treatment,What are the treatments for Pseudopelade of Br...,Is there treatment or a cure for pseudopelade ...,"Pseudopelade of Brocq is a rare, chronic infla...","Pseudopelade of Brocq is a rare, chronic, and ...",Pseudopelade of Brocq is a rare condition that...,NaN
16406,information,What is (are) Desmoplastic small round cell tu...,"Desmoplastic small round cell tumors (DSRCT), ...",Desmoplastic small round cell tumor (DSRCT) is...,Desmoplastic small round cell tumor (DSRCT) is...,Desmoplastic small round cell tumor is a type ...,NaN

In [ ]:
import pandas as pd

# Carica il file Excel (modifica 'file.xlsx' con il nome del tuo file)

# Trova la prima riga in cui la colonna è NaN
prima_riga_nan = df3[df3['Answer_LLM_prompt2'].isna()].index[0]

print("La prima riga con NaN è:", prima_riga_nan)

La prima riga con NaN è: 7700

In [ ]:
prompt_template = f'''[INST]  <<SYS>>

    You are a helpful, respectful and honest Doctor. Always answer as helpfully as possible.

    Answer describing in a scentific way. Be formal during the answer. Use the third person.

    Answer the question in a comprehensive way. Don't use structure in phrase such as Additionally, more ...

    Respond like a Doctor on online forum or a Doctor who is speaking with a patient.

    Question : What are the symptoms of Lymphocytic Choriomeningitis (LCM) ?
    \nAnswer:"

    '''

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/lavoro/Ricerca/CHI/df1csv_caring.csv')

<ipython-input-2-3b1033fdb070>:1: DtypeWarning: Columns (44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/lavoro/Ricerca/CHI/df1csv_caring.csv')

In [ ]:
# Funzione per considerare "vuoto" anche spazi e NaN
def is_effectively_empty(value):
    if pd.isna(value):
        return True
    if isinstance(value, str) and value.strip() == '':
        return True
    return False

# Controlla nella colonna fino alla riga 3599
empty_before_3600 = df.loc[:3599, 'Answer_medico_caring_LLM'].apply(is_effectively_empty)

# Verifica se c'è almeno una cella vuota prima della 3600
if empty_before_3600.any():
    print("❗ Ci sono celle vuote prima della riga 3600.")
    # Se vuoi vedere quali:
    print(df.loc[empty_before_3600, 'Answer_medico_caring_LLM'])
else:
    print("✅ Tutte le celle fino alla riga 3599 sono riempite correttamente.")

✅ Tutte le celle fino alla riga 3599 sono riempite correttamente.

In [ ]:
# Trova il primo indice dove la colonna 'Answer_medico_caring_LLM' è vuota o NaN
first_empty_index = df[df['Answer_medico_caring_LLM_PALMYRA'].isna()].index.min()

# Stampa il risultato
if pd.isna(first_empty_index):
    print("✅ Nessuna riga vuota trovata nella colonna 'Answer_medico_caring_LLM_PALMYRA'.")
else:
    print(f"⚡ Prima riga vuota trovata all'indice: {first_empty_index}")

⚡ Prima riga vuota trovata all'indice: 9729

In [ ]:
print(df.loc[2828, 'Answer_medico_caring_LLM_PALMYRA'])
print(df.loc[2827, 'question'])

To diagnose childhood vascular tumors, we use a combination of tests and procedures. First, we do a physical examination and take a detailed history of your child's health. This helps us identify any signs of disease that may be visible or hidden. Next, we may use an ultrasound exam, which uses sound waves to create images of the inside of the body. This is a painless and non-invasive test that can give us valuable information. If needed, we may also use a CT scan or an MRI, which are advanced imaging tests that provide detailed pictures of the body's internal structures. In some cases, we may need to take a biopsy, which involves removing a small sample of tissue for further examination under a microscope. This helps us confirm the diagnosis and determine the best course of treatment.
What is (are) Childhood Vascular Tumors ?

In [ ]:
df

,context,question,Answer_medico,Answer_LLM,Answer_LLM_PALMYRA,Sentiment_medico,Sentiment_LLM,Sentiment_LLM_PALMYRA,Answer_medico_concepts,Answer_LLM_concepts,...,Answer_LLM_prompt2_GunningFog,Answer_LLM_PALMYRA_prompt2_FleschKincaid,Answer_LLM_PALMYRA_prompt2_GunningFog,Answer_LLM_prompt2_emotions,Answer_LLM_PALMYRA_prompt2_emotions,Answer_medico_emotions,Answer_LLM_emotions,Answer_LLM_PALMYRA_emotions,Answer_medico_caring_LLM,Answer_medico_caring_LLM_PALMYRA
0,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,LCMV infections can occur after exposure to fr...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Individuals who are at risk for Lymphocytic Ch...,Very Negative,Very Negative,Negative,LCMV exposure to fresh urine droppings saliva ...,Lymphocytic Choriomeningitis LCM viral infecti...,...,11.04,12.1,13.20,"{'neutral': np.float64(0.8154), 'approval': np...","{'neutral': np.float64(0.4486), 'caring': np.f...","{'neutral': np.float64(0.81), 'approval': np.f...","{'neutral': np.float64(0.557), 'approval': np....","{'neutral': np.float64(0.8582), 'approval': np...",People who may be at risk for Lymphocytic Chor...,LCM is a viral infection that can be spread th...
1,symptoms,What are the symptoms of Lymphocytic Choriomen...,LCMV is most commonly recognized as causing ne...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Negative,Neutral,Very Negative,LCMV neurological disease implies infection sy...,Lymphocytic Choriomeningitis LCM viral infecti...,...,12.40,10.6,13.48,"{'caring': np.float64(0.5921), 'approval': np....","{'neutral': np.float64(0.5146), 'confusion': n...","{'neutral': np.float64(0.8115), 'approval': np...","{'neutral': np.float64(0.3162), 'confusion': n...","{'neutral': np.float64(0.4024), 'approval': np...",The symptoms of Lymphocytic Choriomeningitis (...,When you get infected with Lymphocytic Choriom...
2,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,Individuals of all ages who come into contact ...,Individuals at risk for Lymphocytic Choriomeni...,Individuals who are at risk for Lymphocytic Ch...,Very Negative,Very Negative,Negative,Individuals ages contact with urine feces sali...,Individuals risk Lymphocytic Choriomeningitis ...,...,10.53,12.1,13.20,"{'neutral': np.float64(0.7154), 'approval': np...","{'neutral': np.float64(0.4486), 'caring': np.f...","{'neutral': np.float64(0.577), 'approval': np....","{'neutral': np.float64(0.5789), 'approval': np...","{'neutral': np.float64(0.8582), 'approval': np...","Anyone, regardless of age, who encounters the ...",People of all ages can get infected with Lymph...
3,exams and tests,How to diagnose Lymphocytic Choriomeningitis (...,"During the first phase of the disease, the mos...",Lymphocytic Choriomeningitis (LCM) is typicall...,To diagnose Lymphocytic Choriomeningitis (LCM)...,Negative,Neutral,Neutral,phase disease laboratory abnormalities white b...,Lymphocytic Choriomeningitis LCM diagnosed cli...,...,10.42,11.1,12.98,"{'neutral': np.float64(0.631), 'approval': np....","{'neutral': np.float64(0.4749), 'approval': np...","{'neutral': np.float64(0.9021), 'realization':...","{'neutral': np.float64(0.7318), 'approval': np...","{'neutral': np.float64(0.9108), 'approval': np...",To diagnose Lymphocytic Choriomeningitis (LCM)...,"To diagnose Lymphocytic Choriomeningitis, we l..."
4,treatment,What are the treatments for Lymphocytic Chorio...,"Aseptic meningitis, encephalitis, or meningoen...",Lymphocytic Choriomeningitis (LCM) is a viral ...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Neutral,Neutral,Neutral,Aseptic meningitis encephalitis meningoencepha...,Lymphocytic Choriomeningitis LCM viral infecti...,...,13.48,12.4,14.23,"{'neutral': np.float64(0.3496), 'approval': np...","{'neutral': np.float64(0.3772), 'caring': np.f...","{'neutral': np.float64(0.7539), 'disapproval':...","{'neutral': np.float64(0.6613), 'caring': np.f...","{'neutral': np.float64(0.5117), 'approval': np...",The treatments for Lymphocytic Choriomeningiti...,"When you have Lymphocytic Choriomeningitis, yo..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16402,symptoms,What are the symptoms of Familial visceral myo...,What are the signs and symptoms of Familial vi...,Familial visceral myopathy with external ophth...,Familial visceral myopathy with external ophth...,Neutral,Very Negative,Very Negative,signs symptoms Familial visceral myopathy exte...,Familial visceral myopathy external ophthalmop...,...,15.41,14.5,15.41,"{'neutral': np.float64(0.3926), 'realization':...","{'neutral': np.float64(0.3926), 'realization':...","{'neutral': np.float64(0.8247), 'curiosity': n...","{'neutral': np.float64(0.8319), 'approval': np...","{'neutral': np.float64(0.8232), 'realization':...",What are the signs and symptoms of Familial vi...,NaN
16403,information,What is (are) Pseudopelade of Brocq ?,Pseudopelade of Brocq (PBB) is a slowly progre...,Pseudopelade of Brocq is a rare type of scarri...,"Pseudopelade of Brocq is a rare, chronic, and ...",Neutral,Very Negative,Very Negative,Pseudopelade Brocq PBB progressive chronic con...,Pseudopelade Brocq scarring alopecia group con...,...,10.95,8.3,10.95,"{'neutral': np.float64(0.6931), 'confusion': n...","{'neutral': np.float64(0.6931), 'confusion': n...","{'confusion': np.float64(0.662), 'neutral': np...","{'neutral': np.float64(0.6695), 'realization':...","{'confusion': np.float64(0.3113), 'neutral': n...","Pseudopelade of Brocq, or PBB, is a long-term ...",NaN
16404,symptoms,What are the symptoms of Pseudopelade of Brocq ?,What are the signs and symptoms of Pseudopelad...,"Pseudopelade of Brocq is a rare, chronic, and ...","Pseudopelade of Brocq is a rare, chronic, and ...",Neutral,Very Negative,Very Negative,signs symptoms Pseudopelade Brocq Human signs ...,Pseudopelade Brocq rare chronic progressive co...,...,11.34,9.3,11.34,"{'caring': np.float64(0.2741), 'neutral': np.f...","{'caring': np.float64(0.2741), 'neutral': np.f...","{'neutral': np.float64(0.8301), 'curiosity': n...","{'neutral': np.float64(0.7161), 'realization':...","{'neutral': np.float64(0.6501), 'sadness': np....",The condition known as Pseudopelade of Brocq c...,NaN
16405,treatment,What are the treatments for Pseudopelade of Br...,Is there treatment or a cure for pseudopelade ...,"Pseudopelade of Brocq is a rare, chronic infla...","Pseudopelade of Brocq is a rare, chronic, and ...",Neutral,Neutral,Neutral,treatment cure pseudopelade Brocq effective tr...,Pseudopelade Brocq rare chronic inflammatory s...,...,12.74,11.2,12.74,"{'caring': np.float64(0.595), 'neutral': np.fl...","{'caring': np.float64(0.595), 'neutral': np.fl...","{'confusion': np.float64(0.2811), 'curiosity':...","{'neutral': np.float64(0.6682), 'approval': np...","{'neutral': np.float64(0.7205), 'approval': np...",I'm sorry to hear that you're dealing with pse...,NaN
16406,information,What is (are) Desmoplastic small round cell tu...,"Desmoplastic small round cell tumors (DSRCT), ...",Desmoplastic small round cell tumor (DSRCT) is...,Desmoplastic small round cell tumor (DSRCT) is...,Very Negative,Neutral,Very Negative,Desmoplastic small round cell tumors DSRCT mal...,Desmoplastic small round cell tumor DSRCT mali...,...,12.85,10.6,12.85,"{'neutral': np.float64(0.832), 'approval': np....","{'neutral': np.float64(0.832), 'approval': np....","{'neutral': np.float64(0.9081), 'approval': np...","{'neutral': np.float64(0.6446), 'approval': np...","{'neutral': np.float64(0.7865), 'approval': np...",A Desmoplastic small round cell tumor (DSRCT) ...,NaN

In [ ]:
from openai import OpenAI
import pandas as pd
import time
import os

def clean_console():
    try:
        # Prova a usare clear_output se siamo in ambiente IPython (Colab, Jupyter)
        from IPython.display import clear_output
        clear_output(wait=True)
    except ImportError:
        # Se non siamo in IPython, prova clear normale
        import os
        os.system('cls' if os.name == 'nt' else 'clear')


def update_dataframe(index, answer):
    """
    Aggiorna il DataFrame `df` aggiungendo la risposta nella colonna 'Answer_medico_caring' corrispondente all'indice.
    """
    global df
    df.loc[index, 'Answer_medico_caring_LLM_PALMYRA'] = answer

# Configura il client OpenAI58299729
client = OpenAI(
    base_url="https://integrate.api.nvidia.com/v1",
    api_key=""
)

# Parametri iniziali
start_index = 9729
num_rows = 10000
save_every = 100  # salva ogni 100 righe
output_path = '/content/drive/MyDrive/lavoro/Ricerca/CHI/df1csv_caring.csv'

count = 0

for index in range(start_index, start_index + num_rows):
    try:
        # Preleva la risposta originale dal DataFrame
        original_answer = df.loc[index, 'Answer_medico']
        question =df.loc[index, 'question']

        # Salta se la risposta è vuota o NaN
        if pd.isna(original_answer) or original_answer.strip() == "":
            continue

        # Costruisci il prompt
        prompt_template = f'''[INST] <<SYS>>
You are a compassionate and trustworthy medical doctor.

Your task is to rephrase the provided medical answer to a certain question to make it easier to understand for someone without a medical background.

Keep the meaning exactly the same, but use a warm, supportive, and caring tone. Speak simply and clearly. Imagine you are explaining it kindly to a patient.

Avoid lists, bullet points, or numbered items. Use short sentences and everyday words. Do not add new information.

Follow the Flesch Kincaid and Gunning Fog Scores standards trying to keep them low for better legibility.

Just reformulate it. Don't add initial phrase.

When necessary, you can try to syntetize it always keeping the initial meaning.

<<SYS>>
Original question: {question}
Original Answer: {original_answer} [/INST]
'''

        # Retry automatico
        retries = 3
        while retries > 0:
            try:
                # Chiamata API senza stream, più veloce
                completion = client.chat.completions.create(
                    model="writer/palmyra-med-70b-32k",
                    #model="mistralai/mixtral-8x22b-instruct-v0.1",
                    messages=[{"role": "user", "content": prompt_template}],
                    temperature=0.2,
                    top_p=0.7,
                    max_tokens=1024,
                    stream=False  # disattiva stream
                )

                rewritten_answer = completion.choices[0].message.content.strip()
                break  # esce dal retry loop se va bene

            except Exception as e:
                print(f"Retrying... Remaining attempts: {retries-1}")
                retries -= 1
                time.sleep(5)  # aspetta un po' prima di riprovare
                if retries == 0:
                    raise e  # rilancia l'eccezione se finiti i tentativi

        # Aggiorna il DataFrame
        update_dataframe(index, rewritten_answer)

        # Stampa output semplice per monitorare
        print(f"Index {index}: {rewritten_answer}\n")

        count += 1

        # Salvataggio ogni `save_every`
        # Salvataggio ogni `save_every`
        if count % save_every == 0:
            df.to_csv(output_path, index=False)
            print(f"🔵 Autosave at index {index} - Data saved to {output_path}")
            time.sleep(1)
            clean_console()

    except Exception as e:
        print(f"❌ Error processing index {index}: {e}")

# Salvataggio finale
df.to_csv(output_path, index=False)
print(f"✅ Processing completed. Final data saved to {output_path}")

Index 11029: Congenital disorder of glycosylation type I/IIX is a condition that affects how our body processes and regulates things. It can cause problems with skin color, seizures in infants, and is usually inherited from both parents. These symptoms can vary from person to person, and we don't always know how often they occur because there isn't a lot of information available.

Index 11030: Acute febrile neutrophilic dermatosis, also called Sweet syndrome, is a skin condition that causes fever, joint pain, and painful skin lesions. It usually appears on the face, neck, back, and arms. It can affect both men and women of all ages, although it's more common in middle-aged women. The exact cause is often unknown, but it can be triggered by infections, illnesses, or certain medications. It can also be associated with some cancers and other serious health issues. Although it usually clears up on its own in a few months, treatment can speed up the healing process.

Index 11031: Acute febrile neutrophilic dermatosis is a condition that causes distinctive skin lesions to appear suddenly, usually after a fever or upper respiratory infection. These lesions start as small red bumps that quickly grow into larger clusters called plaques. They can be tender or painful and may develop blisters, pustules, or even ulcers. The lesions can last for weeks or months before disappearing on their own, but with medical treatment, they can resolve in just a few days. Other symptoms of this condition include moderate to high fever, pink eye, tiredness, aching joints and headache, and mouth ulcers.

Index 11032: Acute febrile neutrophilic dermatosis can be caused by various factors. In many cases, the exact cause is unknown. However, it can be a sign of the immune system responding to certain conditions. These conditions include upper respiratory tract infections like chest infections or strep throat, blood disorders like acute myelogenous leukemia, inflammatory bowel diseases like ulcerative colitis or Crohn's disease, bowel or breast cancer, pregnancy, rheumatoid arthritis, or even an injury at the site where the rash appears, such as an insect bite or needle prick. Additionally, certain medications like nonsteroidal anti-inflammatory drugs can also trigger this condition.

Index 11033: Acute febrile neutrophilic dermatosis can be treated with medications that reduce inflammation and allergic reactions. These medications, called systemic corticosteroids, can improve skin lesions and symptoms in just a few days. The worst of the lesions usually disappear within a few weeks. However, long-term use of these medications can cause problems in children, so doctors try to use other drugs that are safer for them. There are many other treatment options available, and the choice depends on the individual case. Even without treatment, the lesions usually go away on their own within a few months, but they can come back. If there is an underlying cause, treating that condition can help resolve the skin problem and prevent it from coming back.

Index 11034: Q fever is a disease that can affect people all over the world. It has two stages: acute and chronic. It's caused by a type of bacteria called Coxiella burnetii. This bacteria is usually found in animals like cows, sheep, and goats. When these animals give birth, they release fluids that contain the bacteria. The bacteria can survive for a long time in the environment. People usually get infected by breathing in the bacteria that are in the air, which can be contaminated with the birth fluids and waste from infected animals. It's not common for people to get Q fever from tick bites, drinking unpasteurized milk, or from other people. Most people are very susceptible to the disease, and it only takes a few bacteria to cause infection. In very few cases, the acute infection can turn into a chronic infection. Antibiotics are used to treat the acute form of Q fever. The treatment for the chronic form depends on the symptoms.

Index 11035: Osteogenesis imperfecta type II is a condition that affects the bones and can cause several symptoms. These symptoms can vary from person to person, but they often include problems with the bones in the pelvis, ribs, and limbs. The bones may be weak and prone to fractures, and they may also be shaped differently than usual. Some people with this condition may have blue eyes and thin skin. It's also common for babies with this condition to be born prematurely and to have breathing problems. In some cases, the heart may not work properly, leading to heart failure. Overall, this condition can cause a range of physical challenges that require careful management and treatment.

Index 11036: Spondylometaphyseal dysplasia corner fracture type is a condition that affects the bones and can cause a variety of symptoms. The most common symptoms include abnormal hip bones, wrist problems, a small odontoid process in the neck, short limbs, and frequent fractures. People with this condition are also usually shorter than average. Some other symptoms that may occur, although less frequently, include a curved spine, abnormal finger bones, knock-knees, flat feet, and heart defects. This condition is inherited in an autosomal dominant pattern, which means that only one copy of the abnormal gene is needed to cause the condition. It can also cause a waddling gait and irregularities in the ends of the vertebrae.

Index 11037: Maturity-onset diabetes of the young, type 5 is a condition that can cause a variety of symptoms. Some of the most common ones include multicystic kidney dysplasia, which is a problem with the kidneys, and nephropathy, which is damage to the kidneys. It can also cause diabetes mellitus, which is a condition where the body has trouble regulating blood sugar levels. Other symptoms may include problems with the liver, such as elevated hepatic transaminases, and problems with the kidneys, such as elevated serum creatinine and proteinuria. Some people may also experience glucose intolerance, which means they have trouble processing sugar, and glycosuria, which is the presence of sugar in the urine. Additionally, there may be signs of gout, which is a type of arthritis, and stage 5 chronic kidney disease, which is a severe stage of kidney disease. Less common symptoms may include abnormalities of the reproductive system, cognitive impairment, and hearing impairment. It's important to note that not everyone with this condition will have all of these symptoms, and the severity of the symptoms can vary from person to person.

Index 11038: Danon disease is a rare condition where the cell's recycling system doesn't work properly. This is because of a problem with the wall of a special compartment inside the cell called a lysosome. The problem is caused by a change in a specific gene. The main symptom of Danon disease is heart disease, but other symptoms can also occur. It is usually passed down from parents to children in a way that affects boys more severely than girls. Girls who carry the changed gene may or may not have symptoms.

Index 11039: Danon disease is a condition that affects the heart and can cause serious problems. It can make the heart muscle become thicker and less efficient, which can lead to complications like sudden death. People with Danon disease may also have high levels of a certain enzyme in their blood, problems with their eyesight, and abnormal heart rhythms. Men with the condition usually develop heart problems before the age of 20, while women may not develop them until later in life. Some women who carry the gene mutation may not have any symptoms at all. Other symptoms that can occur include learning difficulties, muscle weakness, and exercise intolerance. These symptoms can be similar to those of another heart condition called hypertrophic cardiomyopathy, but they are caused by different things.

Index 11040: Danon disease is caused by a change in a specific gene called LAMP2. This gene is responsible for helping cells break down and recycle materials properly.

Index 11041: Danon disease is passed down from parents to children in a special way called X-linked inheritance. This means that the gene responsible for the disease is located on the X chromosome. To learn more about how this type of inheritance works, you can visit the Centre for Genetics Education website.

Index 11042: To diagnose Danon disease, we can use genetic testing. This is a special kind of test that helps us understand if you or your family have the disease and how it might affect your health. It can also help us decide on the best treatment options. If you're interested in getting tested, you should talk to your doctor or a genetic professional who can guide you through the process and explain your options. They can also give you a list of laboratories that offer this type of testing.

Index 11043: To treat the heart condition in Danon disease, we need to keep a close eye on how it's progressing. If the heart disease is getting worse quickly, we might suggest some aggressive treatments like a heart transplant or a special device that helps regulate the heart rhythm. However, the severity of the heart condition can vary, especially in females. So, the treatment plan will be personalized based on how severe the heart disease is and what the patient needs.

Index 11044: When it comes to Onychodystrophy-anonychia, there are certain signs and symptoms that people with this condition may experience. These can include tapered finger bones, missing nails, and problems with the nails that are present. It's also possible for people with this condition to be born with hip dislocation. These symptoms can vary from person to person, and not everyone will have all of them. It's important to remember that this condition is inherited and can be passed down from parents to their children.

Index 11045: Hermansky Pudlak syndrome 2 is a rare condition that affects many parts of the body. People with this condition may have problems with their skin, hair, eyes, and teeth. They might have fair hair, light skin, and eyes that are sensitive to light. Their teeth may be weak and prone to cavities, and their gums may be unhealthy. They may also have problems with their hips and legs, which can cause walking difficulties. Some people with this condition have intellectual disabilities, which means they may learn more slowly than others. They might also have trouble seeing and hearing, and may have frequent infections. The condition is usually inherited from parents who carry the gene, and it is present from birth. It's important for people with this condition to receive regular medical care to manage their symptoms and prevent complications.

Index 11046: Ehlers-Danlos syndrome is a group of genetic disorders that affect the connective tissue in our bodies. It's caused by problems with the way collagen is made or used. There are six main types of EDS, and they can cause a wide range of symptoms. Some people with EDS have very flexible joints and skin that stretches easily and bruises easily. The severity of the symptoms can vary from mild to life-threatening. The condition is usually inherited, but sometimes the exact cause is unknown. There is no cure for EDS, but treatment focuses on managing the symptoms and preventing complications.

Index 11047: Ehlers-Danlos syndrome is a condition that affects the body's connective tissues, which are like the glue that holds everything together. There are six main types of Ehlers-Danlos syndrome, and each one has its own set of symptoms. The symptoms can vary from person to person, but they often include joint problems like hypermobility, which means the joints can move more than they should. This can lead to dislocations and partial dislocations, which can be painful and cause problems with movement. Skin problems are also common, like skin that bruises easily and scars that are flat and depressed. Some people with Ehlers-Danlos syndrome may also have muscle and bone pain, and they might have trouble with their muscles and joints from a young age. The vascular type of Ehlers-Danlos syndrome is very serious because it can cause arteries and organs to rupture, which can be life-threatening. People with this type often have thin skin, short stature, and a distinctive appearance. The kyphoscoliosis type is characterized by severe muscle weakness at birth, delayed development, and a curved spine. The arthrochalasia type is similar, but it also includes congenital hip dislocation. The dermatosparaxis type is known for extremely fragile skin that bruises and scars easily, along with saggy skin and hernias. It's important to get a proper diagnosis and treatment plan if you think you or someone you know might have Ehlers-Danlos syndrome.

Index 11048: Ehlers-Danlos syndrome is caused by changes in certain genes that affect the production of collagen, a protein that gives strength and structure to our connective tissues. These changes can weaken the tissues in our skin, bones, blood vessels, and organs, leading to the symptoms of the disorder.

Index 11049: Ehlers-Danlos syndrome can be inherited in different ways depending on the type of the condition. For most types, if one parent has the condition, there's a 50% chance that their child will also have it. This is because the condition is caused by a change in one gene, and if one parent has that change, they can pass it on to their child. In some cases, the condition can occur even if neither parent has it, because of a new change in the gene. There are also some types of Ehlers-Danlos syndrome that are inherited in a different way, where both parents must carry a changed gene for their child to have the condition. Even if the parents don't have the condition themselves, they can still pass it on to their child if they both carry the changed gene.

Index 11050: To diagnose Ehlers-Danlos syndrome, we look for specific signs and symptoms. We might also do some tests to help confirm the diagnosis. For some types of the condition, we take a small sample of skin to examine the collagen, which is a protein that helps hold our bodies together. Genetic testing can be done for some types of Ehlers-Danlos syndrome, but not for the most common type. We might also use imaging tests like CT scans or MRIs to get a better look at how the condition is affecting your body. In some cases, we might test your urine to see if there are any problems with the enzymes that help build collagen.

Index 11051: We don't have a specific cure for Ehlers-Danlos syndrome, but we can treat its symptoms and prevent serious complications. The treatment plan depends on the type of EDS you have, so it's different for each type. We have specific strategies for each type to manage the symptoms and prevent problems. If you have any questions about your treatment, please talk to your doctor.

Index 11052: Polycystic kidney disease is a group of inherited kidney disorders where many cysts, which are like fluid-filled sacs, grow in both kidneys. These cysts replace the normal kidney tissue and interfere with the kidneys' ability to filter waste products from the blood. As the cysts grow, the kidneys become enlarged and can eventually fail. Cysts can also appear in other organs, like the liver. The severity of the signs and symptoms can vary greatly from person to person. Treatment is tailored to each individual based on their specific signs and symptoms. There are two main types of polycystic kidney disease: autosomal dominant polycystic kidney disease, which usually causes symptoms between the ages of 30 and 40, and autosomal recessive polycystic kidney disease, which is a rare form that usually causes symptoms in infancy and early childhood and can be lethal early in life.

Index 11053: Polycystic kidney disease is a condition where multiple cysts develop in both kidneys, affecting their ability to filter waste from the blood. As the disease progresses, the cysts cause the kidneys to enlarge and can lead to kidney failure. Cysts can also appear in other organs, like the liver. Common complications include high blood pressure, severe back or side pain, blood in the urine, urinary tract infections, kidney stones, and heart valve problems. People with this condition are also at risk for a brain aneurysm, which can be life-threatening if it ruptures. Other symptoms may include anemia, abnormal development, respiratory issues, and reduced bone density.

Index 11054: Autoimmune autonomic ganglionopathy is a rare condition where your immune system mistakenly attacks and damages parts of your nervous system that control things like your blood pressure, digestion, and bladder function. This can cause a range of symptoms including dizziness when you stand up, fainting, constipation, and dry eyes and mouth. The exact cause of this condition is not well understood, and because it's so rare, there isn't a standard treatment. However, some people have been helped by treatments like plasmapheresis, intravenous immunoglobulin, and medications that suppress the immune system. In some cases, people may get better on their own, but the recovery is often not complete.

Index 11055: The symptoms of autoimmune autonomic ganglionopathy can be quite varied. One of the main symptoms is severe low blood pressure when you stand up, which can last for weeks or even years. This can cause you to feel faint or even pass out. You may also experience constipation and problems with your digestive system, like food not moving through your body properly. Some people may have trouble urinating because their bladder doesn't empty completely. Another symptom is having pupils that are fixed and dilated, which means they don't change size like they normally would. Additionally, you might have a dry mouth and eyes. Some people with this condition also have symptoms similar to a condition called postural orthostatic tachycardia syndrome, or POTS.

Index 11056: Autoimmune autonomic ganglionopathy is a condition where the immune system mistakenly attacks a receptor in the autonomic ganglia, which is part of the peripheral autonomic nerve fiber. This attack leads to damage in the ganglia. In many cases, this condition is linked to high levels of a specific antibody called ganglionic acetylcholine receptor antibody. Interestingly, about 60% of cases occur after an infection or another illness.

Index 11057: To treat autoimmune autonomic ganglionopathy, doctors usually try different approaches because there is no one standard treatment for this rare condition. They might use plasma exchange or total plasmapheresis, which involves replacing the plasma in your blood with new plasma. Another option is intravenous immunoglobulin (IVIG), which gives you antibodies to help your immune system. They might also use IV corticosteroids or immunosuppressive drugs like Rituxan to reduce inflammation and control your immune system. There is also an ongoing study called the Autonomic Disorders Consortium that is testing new treatments for this condition.

Index 11058: Priapism is a condition that can cause certain signs and symptoms. These symptoms can vary from person to person, but they are usually related to problems with the penis. The most common symptom is a painful erection that lasts for a long time. This erection is not related to sexual arousal and can be very uncomfortable. It's important to seek medical attention if you experience this symptom because it can cause serious complications if left untreated. Other symptoms may include difficulty urinating or feeling the need to urinate frequently. If you have any of these symptoms, it's important to see a doctor as soon as possible so they can help you manage them and prevent any further problems.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df

,context,question,Answer_medico,Answer_LLM,Answer_LLM_PALMYRA,Sentiment_medico,Sentiment_LLM,Sentiment_LLM_PALMYRA,Answer_medico_concepts,Answer_LLM_concepts,...,Answer_LLM_prompt2_FleschKincaid,Answer_LLM_prompt2_GunningFog,Answer_LLM_PALMYRA_prompt2_FleschKincaid,Answer_LLM_PALMYRA_prompt2_GunningFog,Answer_LLM_prompt2_emotions,Answer_LLM_PALMYRA_prompt2_emotions,Answer_medico_emotions,Answer_LLM_emotions,Answer_LLM_PALMYRA_emotions,Answer_medico_caring_LLM
0,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,LCMV infections can occur after exposure to fr...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Individuals who are at risk for Lymphocytic Ch...,Very Negative,Very Negative,Negative,LCMV exposure to fresh urine droppings saliva ...,Lymphocytic Choriomeningitis LCM viral infecti...,...,9.9,11.04,12.1,13.20,"{'neutral': np.float64(0.8154), 'approval': np...","{'neutral': np.float64(0.4486), 'caring': np.f...","{'neutral': np.float64(0.81), 'approval': np.f...","{'neutral': np.float64(0.557), 'approval': np....","{'neutral': np.float64(0.8582), 'approval': np...",LCMV infections can happen when you come into ...
1,symptoms,What are the symptoms of Lymphocytic Choriomen...,LCMV is most commonly recognized as causing ne...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Negative,Neutral,Very Negative,LCMV neurological disease implies infection sy...,Lymphocytic Choriomeningitis LCM viral infecti...,...,11.5,12.40,10.6,13.48,"{'caring': np.float64(0.5921), 'approval': np....","{'neutral': np.float64(0.5146), 'confusion': n...","{'neutral': np.float64(0.8115), 'approval': np...","{'neutral': np.float64(0.3162), 'confusion': n...","{'neutral': np.float64(0.4024), 'approval': np...","LCMV, or Lymphocytic Choriomeningitis Virus, i..."
2,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,Individuals of all ages who come into contact ...,Individuals at risk for Lymphocytic Choriomeni...,Individuals who are at risk for Lymphocytic Ch...,Very Negative,Very Negative,Negative,Individuals ages contact with urine feces sali...,Individuals risk Lymphocytic Choriomeningitis ...,...,10.3,10.53,12.1,13.20,"{'neutral': np.float64(0.7154), 'approval': np...","{'neutral': np.float64(0.4486), 'caring': np.f...","{'neutral': np.float64(0.577), 'approval': np....","{'neutral': np.float64(0.5789), 'approval': np...","{'neutral': np.float64(0.8582), 'approval': np...","Anyone who comes into contact with the urine, ..."
3,exams and tests,How to diagnose Lymphocytic Choriomeningitis (...,"During the first phase of the disease, the mos...",Lymphocytic Choriomeningitis (LCM) is typicall...,To diagnose Lymphocytic Choriomeningitis (LCM)...,Negative,Neutral,Neutral,phase disease laboratory abnormalities white b...,Lymphocytic Choriomeningitis LCM diagnosed cli...,...,9.3,10.42,11.1,12.98,"{'neutral': np.float64(0.631), 'approval': np....","{'neutral': np.float64(0.4749), 'approval': np...","{'neutral': np.float64(0.9021), 'realization':...","{'neutral': np.float64(0.7318), 'approval': np...","{'neutral': np.float64(0.9108), 'approval': np...","During the early stage of the illness, it's co..."
4,treatment,What are the treatments for Lymphocytic Chorio...,"Aseptic meningitis, encephalitis, or meningoen...",Lymphocytic Choriomeningitis (LCM) is a viral ...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Neutral,Neutral,Neutral,Aseptic meningitis encephalitis meningoencepha...,Lymphocytic Choriomeningitis LCM viral infecti...,...,11.8,13.48,12.4,14.23,"{'neutral': np.float64(0.3496), 'approval': np...","{'neutral': np.float64(0.3772), 'caring': np.f...","{'neutral': np.float64(0.7539), 'disapproval':...","{'neutral': np.float64(0.6613), 'caring': np.f...","{'neutral': np.float64(0.5117), 'approval': np...","My dear friend, if you're diagnosed with asept..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16402,symptoms,What are the symptoms of Familial visceral myo...,What are the signs and symptoms of Familial vi...,Familial visceral myopathy with external ophth...,Familial visceral myopathy with external ophth...,Neutral,Very Negative,Very Negative,signs symptoms Familial visceral myopathy exte...,Familial visceral myopathy external ophthalmop...,...,14.5,15.41,14.5,15.41,"{'neutral': np.float64(0.3926), 'realization':...","{'neutral': np.float64(0.3926), 'realization':...","{'neutral': np.float64(0.8247), 'curiosity': n...","{'neutral': np.float64(0.8319), 'approval': np...","{'neutral': np.float64(0.8232), 'realization':...",NaN
16403,information,What is (are) Pseudopelade of Brocq ?,Pseudopelade of Brocq (PBB) is a slowly progre...,Pseudopelade of Brocq is a rare type of scarri...,"Pseudopelade of Brocq is a rare, chronic, and ...",Neutral,Very Negative,Very Negative,Pseudopelade Brocq PBB progressive chronic con...,Pseudopelade Brocq scarring alopecia group con...,...,8.3,10.95,8.3,10.95,"{'neutral': np.float64(0.6931), 'confusion': n...","{'neutral': np.float64(0.6931), 'confusion': n...","{'confusion': np.float64(0.662), 'neutral': np...","{'neutral': np.float64(0.6695), 'realization':...","{'confusion': np.float64(0.3113), 'neutral': n...",NaN
16404,symptoms,What are the symptoms of Pseudopelade of Brocq ?,What are the signs and symptoms of Pseudopelad...,"Pseudopelade of Brocq is a rare, chronic, and ...","Pseudopelade of Brocq is a rare, chronic, and ...",Neutral,Very Negative,Very Negative,signs symptoms Pseudopelade Brocq Human signs ...,Pseudopelade Brocq rare chronic progressive co...,...,9.3,11.34,9.3,11.34,"{'caring': np.float64(0.2741), 'neutral': np.f...","{'caring': np.float64(0.2741), 'neutral': np.f...","{'neutral': np.float64(0.8301), 'curiosity': n...","{'neutral': np.float64(0.7161), 'realization':...","{'neutral': np.float64(0.6501), 'sadness': np....",NaN
16405,treatment,What are the treatments for Pseudopelade of Br...,Is there treatment or a cure for pseudopelade ...,"Pseudopelade of Brocq is a rare, chronic infla...","Pseudopelade of Brocq is a rare, chronic, and ...",Neutral,Neutral,Neutral,treatment cure pseudopelade Brocq effective tr...,Pseudopelade Brocq rare chronic inflammatory s...,...,11.2,12.74,11.2,12.74,"{'caring': np.float64(0.595), 'neutral': np.fl...","{'caring': np.float64(0.595), 'neutral': np.fl...","{'confusion': np.float64(0.2811), 'curiosity':...","{'neutral': np.float64(0.6682), 'approval': np...","{'neutral': np.float64(0.7205), 'approval': np...",NaN
16406,information,What is (are) Desmoplastic small round cell tu...,"Desmoplastic small round cell tumors (DSRCT), ...",Desmoplastic small round cell tumor (DSRCT) is...,Desmoplastic small round cell tumor (DSRCT) is...,Very Negative,Neutral,Very Negative,Desmoplastic small round cell tumors DSRCT mal...,Desmoplastic small round cell tumor DSRCT mali...,...,10.6,12.85,10.6,12.85,"{'neutral': np.float64(0.832), 'approval': np....","{'neutral': np.float64(0.832), 'approval': np....","{'neutral': np.float64(0.9081), 'approval': np...","{'neutral': np.float64(0.6446), 'approval': np...","{'neutral': np.float64(0.7865), 'approval': np...",NaN

In [ ]:
from openai import OpenAI
import pandas as pd

def update_dataframe(index, answer):
    """
    Aggiorna il DataFrame `df` aggiungendo la risposta nella colonna 'Answer_medico_caring' corrispondente all'indice.
    """
    global df  # Assicura che `df` sia accessibile globalmente
    df.loc[index, 'Answer_medico_caring_LLM'] = answer  # Scrive nella nuova colonna

# Configura il client OpenAI
client = OpenAI(
    base_url="https://integrate.api.nvidia.com/v1",
    api_key=""
)

# Parametri iniziali
start_index = 0  # Modifica questo valore in base alle necessità
num_rows = 15000  # Modifica questo valore in base alle necessità
count = 0

# Itera sulle righe del DataFrame
for index in range(start_index, start_index + num_rows):
    try:
        # Preleva la risposta originale dal DataFrame
        original_answer = df.loc[index, 'Answer_medico']

        # Salta se la risposta è vuota o NaN
        if pd.isna(original_answer) or original_answer.strip() == "":
            continue

        # Costruisci il prompt
        prompt_template = f'''[INST] <<SYS>>
You are a compassionate and trustworthy medical doctor.

Your task is to rephrase the provided medical answer to make it easier to understand for someone without a medical background.

Keep the meaning exactly the same, but use a warm, supportive, and caring tone. Speak simply and clearly. Imagine you are explaining it kindly to a patient.

Avoid lists, bullet points, or numbered items. Use short sentences and everyday words. Do not add new information.

<<SYS>>

Original Answer: {original_answer} [/INST]
'''

        # Chiamata API
        completion = client.chat.completions.create(
            #model="writer/palmyra-med-70b-32k",
            model="mistralai/mixtral-8x22b-instruct-v0.1",
            messages=[{"role": "user", "content": prompt_template}],
            temperature=0.2,
            top_p=0.7,
            max_tokens=1024,
            stream=True
        )

        # Raccogli la risposta
        rewritten_answer = ""
        for chunk in completion:
            if chunk.choices[0].delta.content:
                rewritten_answer += chunk.choices[0].delta.content

        # Aggiorna il DataFrame con la risposta rielaborata
        update_dataframe(index, rewritten_answer)

        # Salvataggi periodici
        count += 1
        if count == 50:
            print(f"Saved at index {index}")
            df.to_csv('/content/drive/MyDrive/lavoro/Ricerca/CHI/df1csv_versione2_0.csv', index=False)
            count = 0
        else:
            print(f"Processed count: {count}")

    except Exception as e:
        print(f"Error processing index {index}: {e}")

# Salvataggio finale
df.to_csv('/content/drive/MyDrive/lavoro/Ricerca/CHI/df1csv_versione2_0.csv', index=False)

In [ ]:
from openai import OpenAI
import pandas as pd

def update_dataframe(index, answer):
    """
    Aggiorna il DataFrame `df3` aggiungendo la risposta nella colonna 'Answer_LLM' corrispondente all'indice.
    """
    global df3  # Assicura che `df3` sia accessibile globalmente
    df3.loc[index, 'Answer_LLM_prompt2'] = answer  # Inserisci la risposta nella colonna 'Answer_LLM'


# Configura il client OpenAI
client = OpenAI(
    base_url="https://integrate.api.nvidia.com/v1",
    api_key=""
)

# Parametri iniziali
start_index =  0 # Modifica questo valore in base alle necessità
num_rows = 15000 # Modifica questo valore in base alle necessità
count = 0
# Itera sulle righe del DataFrame
for index in range(start_index, start_index + num_rows):
    try:
        # Preleva la domanda dal DataFrame
        query = df3.loc[index, 'question']

        # Costruisci il prompt
        prompt_template = f'''[INST] <<SYS>>

You are a compassionate and trustworthy medical doctor.

Your task is to answer medical questions using the provided context. Your answer must be easy to understand for someone without a medical background.

Speak in a simple, clear, and kind way. Use everyday language. Avoid jargon, or explain it if necessary. Keep sentences short and vocabulary accessible.

The goal is to help the reader understand, not to impress with technical detail. Imagine you are speaking to a patient or answering on a health forum.

Do not use lists, bullet points, or numbered items. Avoid formal phrases like "in conclusion", "furthermore", or "in addition".

Keep the tone warm and supportive, like a caring doctor who takes time to make sure the patient truly understands.

<<SYS>>

Question: {query} [/INST]
'''


        # Chiamata API
        completion = client.chat.completions.create(
            #model="writer/palmyra-med-70b-32k",
            model="mistralai/mixtral-8x22b-instruct-v0.1",
            messages=[{"role": "user", "content": prompt_template}],
            #temperature=0.5,
            #top_p=1,
            #max_tokens=1024,
            #stream=True
            temperature=0.2,
            top_p=0.7,
            max_tokens=1024,
            stream=True
        )

        # Raccogli la risposta
        Risposta = ""
        for chunk in completion:
            if chunk.choices[0].delta.content:
                Risposta += chunk.choices[0].delta.content

        # Debug: Controlla la risposta
       # print(f"Response for index {index}:\n{Risposta}")

        # Aggiorna il DataFrame con la risposta
        update_dataframe(index, Risposta)
        count = count + 1
        if (count == 50):
          print(f"Response for index {index}:\n{Risposta}")
          df3.to_csv('/content/drive/MyDrive/lavoro/Ricerca/CHI/df1csv.csv', index=False)
          count = 0
        else:
          print(f"count arrivato a: {count}")

    except Exception as e:
        print(f"Error processing index {index}: {e}")

df3.to_csv('/content/drive/MyDrive/lavoro/Ricerca/CHI/df1csv.csv', index=False)

Output streaming troncato alle ultime 5000 righe.
Error processing index 17700: 17700
Error processing index 17701: 17701
Error processing index 17702: 17702
Error processing index 17703: 17703
Error processing index 17704: 17704
Error processing index 17705: 17705
Error processing index 17706: 17706
Error processing index 17707: 17707
Error processing index 17708: 17708
Error processing index 17709: 17709
Error processing index 17710: 17710
Error processing index 17711: 17711
Error processing index 17712: 17712
Error processing index 17713: 17713
Error processing index 17714: 17714
Error processing index 17715: 17715
Error processing index 17716: 17716
Error processing index 17717: 17717
Error processing index 17718: 17718
Error processing index 17719: 17719
Error processing index 17720: 17720
Error processing index 17721: 17721
Error processing index 17722: 17722
Error processing index 17723: 17723
Error processing index 17724: 17724
Error processing index 17725: 17725
Error processing index 17726: 17726
Error processing index 17727: 17727
Error processing index 17728: 17728
Error processing index 17729: 17729
Error processing index 17730: 17730
Error processing index 17731: 17731
Error processing index 17732: 17732
Error processing index 17733: 17733
Error processing index 17734: 17734
Error processing index 17735: 17735
Error processing index 17736: 17736
Error processing index 17737: 17737
Error processing index 17738: 17738
Error processing index 17739: 17739
Error processing index 17740: 17740
Error processing index 17741: 17741
Error processing index 17742: 17742
Error processing index 17743: 17743
Error processing index 17744: 17744
Error processing index 17745: 17745
Error processing index 17746: 17746
Error processing index 17747: 17747
Error processing index 17748: 17748
Error processing index 17749: 17749
Error processing index 17750: 17750
Error processing index 17751: 17751
Error processing index 17752: 17752
Error processing index 17753: 17753
Error processing index 17754: 17754
Error processing index 17755: 17755
Error processing index 17756: 17756
Error processing index 17757: 17757
Error processing index 17758: 17758
Error processing index 17759: 17759
Error processing index 17760: 17760
Error processing index 17761: 17761
Error processing index 17762: 17762
Error processing index 17763: 17763
Error processing index 17764: 17764
Error processing index 17765: 17765
Error processing index 17766: 17766
Error processing index 17767: 17767
Error processing index 17768: 17768
Error processing index 17769: 17769
Error processing index 17770: 17770
Error processing index 17771: 17771
Error processing index 17772: 17772
Error processing index 17773: 17773
Error processing index 17774: 17774
Error processing index 17775: 17775
Error processing index 17776: 17776
Error processing index 17777: 17777
Error processing index 17778: 17778
Error processing index 17779: 17779
Error processing index 17780: 17780
Error processing index 17781: 17781
Error processing index 17782: 17782
Error processing index 17783: 17783
Error processing index 17784: 17784
Error processing index 17785: 17785
Error processing index 17786: 17786
Error processing index 17787: 17787
Error processing index 17788: 17788
Error processing index 17789: 17789
Error processing index 17790: 17790
Error processing index 17791: 17791
Error processing index 17792: 17792
Error processing index 17793: 17793
Error processing index 17794: 17794
Error processing index 17795: 17795
Error processing index 17796: 17796
Error processing index 17797: 17797
Error processing index 17798: 17798
Error processing index 17799: 17799
Error processing index 17800: 17800
Error processing index 17801: 17801
Error processing index 17802: 17802
Error processing index 17803: 17803
Error processing index 17804: 17804
Error processing index 17805: 17805
Error processing index 17806: 17806
Error processing index 17807: 17807
Error processing index 17808: 17808
Error processing index 17809: 17809
Error processing index 17810: 17810
Error processing index 17811: 17811
Error processing index 17812: 17812
Error processing index 17813: 17813
Error processing index 17814: 17814
Error processing index 17815: 17815
Error processing index 17816: 17816
Error processing index 17817: 17817
Error processing index 17818: 17818
Error processing index 17819: 17819
Error processing index 17820: 17820
Error processing index 17821: 17821
Error processing index 17822: 17822
Error processing index 17823: 17823
Error processing index 17824: 17824
Error processing index 17825: 17825
Error processing index 17826: 17826
Error processing index 17827: 17827
Error processing index 17828: 17828
Error processing index 17829: 17829
Error processing index 17830: 17830
Error processing index 17831: 17831
Error processing index 17832: 17832
Error processing index 17833: 17833
Error processing index 17834: 17834
Error processing index 17835: 17835
Error processing index 17836: 17836
Error processing index 17837: 17837
Error processing index 17838: 17838
Error processing index 17839: 17839
Error processing index 17840: 17840
Error processing index 17841: 17841
Error processing index 17842: 17842
Error processing index 17843: 17843
Error processing index 17844: 17844
Error processing index 17845: 17845
Error processing index 17846: 17846
Error processing index 17847: 17847
Error processing index 17848: 17848
Error processing index 17849: 17849
Error processing index 17850: 17850
Error processing index 17851: 17851
Error processing index 17852: 17852
Error processing index 17853: 17853
Error processing index 17854: 17854
Error processing index 17855: 17855
Error processing index 17856: 17856
Error processing index 17857: 17857
Error processing index 17858: 17858
Error processing index 17859: 17859
Error processing index 17860: 17860
Error processing index 17861: 17861
Error processing index 17862: 17862
Error processing index 17863: 17863
Error processing index 17864: 17864
Error processing index 17865: 17865
Error processing index 17866: 17866
Error processing index 17867: 17867
Error processing index 17868: 17868
Error processing index 17869: 17869
Error processing index 17870: 17870
Error processing index 17871: 17871
Error processing index 17872: 17872
Error processing index 17873: 17873
Error processing index 17874: 17874
Error processing index 17875: 17875
Error processing index 17876: 17876
Error processing index 17877: 17877
Error processing index 17878: 17878
Error processing index 17879: 17879
Error processing index 17880: 17880
Error processing index 17881: 17881
Error processing index 17882: 17882
Error processing index 17883: 17883
Error processing index 17884: 17884
Error processing index 17885: 17885
Error processing index 17886: 17886
Error processing index 17887: 17887
Error processing index 17888: 17888
Error processing index 17889: 17889
Error processing index 17890: 17890
Error processing index 17891: 17891
Error processing index 17892: 17892
Error processing index 17893: 17893
Error processing index 17894: 17894
Error processing index 17895: 17895
Error processing index 17896: 17896
Error processing index 17897: 17897
Error processing index 17898: 17898
Error processing index 17899: 17899
Error processing index 17900: 17900
Error processing index 17901: 17901
Error processing index 17902: 17902
Error processing index 17903: 17903
Error processing index 17904: 17904
Error processing index 17905: 17905
Error processing index 17906: 17906
Error processing index 17907: 17907
Error processing index 17908: 17908
Error processing index 17909: 17909
Error processing index 17910: 17910
Error processing index 17911: 17911
Error processing index 17912: 17912
Error processing index 17913: 17913
Error processing index 17914: 17914
Error processing index 17915: 17915
Error processing index 17916: 17916
Error processing index 17917: 17917
Error processing index 17918: 17918
Error processing index 17919: 17919
Error processing index 17920: 17920
Error processing index 17921: 17921
Error processing index 17922: 17922
Error processing index 17923: 17923
Error processing index 17924: 17924
Error processing index 17925: 17925
Error processing index 17926: 17926
Error processing index 17927: 17927
Error processing index 17928: 17928
Error processing index 17929: 17929
Error processing index 17930: 17930
Error processing index 17931: 17931
Error processing index 17932: 17932
Error processing index 17933: 17933
Error processing index 17934: 17934
Error processing index 17935: 17935
Error processing index 17936: 17936
Error processing index 17937: 17937
Error processing index 17938: 17938
Error processing index 17939: 17939
Error processing index 17940: 17940
Error processing index 17941: 17941
Error processing index 17942: 17942
Error processing index 17943: 17943
Error processing index 17944: 17944
Error processing index 17945: 17945
Error processing index 17946: 17946
Error processing index 17947: 17947
Error processing index 17948: 17948
Error processing index 17949: 17949
Error processing index 17950: 17950
Error processing index 17951: 17951
Error processing index 17952: 17952
Error processing index 17953: 17953
Error processing index 17954: 17954
Error processing index 17955: 17955
Error processing index 17956: 17956
Error processing index 17957: 17957
Error processing index 17958: 17958
Error processing index 17959: 17959
Error processing index 17960: 17960
Error processing index 17961: 17961
Error processing index 17962: 17962
Error processing index 17963: 17963
Error processing index 17964: 17964
Error processing index 17965: 17965
Error processing index 17966: 17966
Error processing index 17967: 17967
Error processing index 17968: 17968
Error processing index 17969: 17969
Error processing index 17970: 17970
Error processing index 17971: 17971
Error processing index 17972: 17972
Error processing index 17973: 17973
Error processing index 17974: 17974
Error processing index 17975: 17975
Error processing index 17976: 17976
Error processing index 17977: 17977
Error processing index 17978: 17978
Error processing index 17979: 17979
Error processing index 17980: 17980
Error processing index 17981: 17981
Error processing index 17982: 17982
Error processing index 17983: 17983
Error processing index 17984: 17984
Error processing index 17985: 17985
Error processing index 17986: 17986
Error processing index 17987: 17987
Error processing index 17988: 17988
Error processing index 17989: 17989
Error processing index 17990: 17990
Error processing index 17991: 17991
Error processing index 17992: 17992
Error processing index 17993: 17993
Error processing index 17994: 17994
Error processing index 17995: 17995
Error processing index 17996: 17996
Error processing index 17997: 17997
Error processing index 17998: 17998
Error processing index 17999: 17999
Error processing index 18000: 18000
Error processing index 18001: 18001
Error processing index 18002: 18002
Error processing index 18003: 18003
Error processing index 18004: 18004
Error processing index 18005: 18005
Error processing index 18006: 18006
Error processing index 18007: 18007
Error processing index 18008: 18008
Error processing index 18009: 18009
Error processing index 18010: 18010
Error processing index 18011: 18011
Error processing index 18012: 18012
Error processing index 18013: 18013
Error processing index 18014: 18014
Error processing index 18015: 18015
Error processing index 18016: 18016
Error processing index 18017: 18017
Error processing index 18018: 18018
Error processing index 18019: 18019
Error processing index 18020: 18020
Error processing index 18021: 18021
Error processing index 18022: 18022
Error processing index 18023: 18023
Error processing index 18024: 18024
Error processing index 18025: 18025
Error processing index 18026: 18026
Error processing index 18027: 18027
Error processing index 18028: 18028
Error processing index 18029: 18029
Error processing index 18030: 18030
Error processing index 18031: 18031
Error processing index 18032: 18032
Error processing index 18033: 18033
Error processing index 18034: 18034
Error processing index 18035: 18035
Error processing index 18036: 18036
Error processing index 18037: 18037
Error processing index 18038: 18038
Error processing index 18039: 18039
Error processing index 18040: 18040
Error processing index 18041: 18041
Error processing index 18042: 18042
Error processing index 18043: 18043
Error processing index 18044: 18044
Error processing index 18045: 18045
Error processing index 18046: 18046
Error processing index 18047: 18047
Error processing index 18048: 18048
Error processing index 18049: 18049
Error processing index 18050: 18050
Error processing index 18051: 18051
Error processing index 18052: 18052
Error processing index 18053: 18053
Error processing index 18054: 18054
Error processing index 18055: 18055
Error processing index 18056: 18056
Error processing index 18057: 18057
Error processing index 18058: 18058
Error processing index 18059: 18059
Error processing index 18060: 18060
Error processing index 18061: 18061
Error processing index 18062: 18062
Error processing index 18063: 18063
Error processing index 18064: 18064
Error processing index 18065: 18065
Error processing index 18066: 18066
Error processing index 18067: 18067
Error processing index 18068: 18068
Error processing index 18069: 18069
Error processing index 18070: 18070
Error processing index 18071: 18071
Error processing index 18072: 18072
Error processing index 18073: 18073
Error processing index 18074: 18074
Error processing index 18075: 18075
Error processing index 18076: 18076
Error processing index 18077: 18077
Error processing index 18078: 18078
Error processing index 18079: 18079
Error processing index 18080: 18080
Error processing index 18081: 18081
Error processing index 18082: 18082
Error processing index 18083: 18083
Error processing index 18084: 18084
Error processing index 18085: 18085
Error processing index 18086: 18086
Error processing index 18087: 18087
Error processing index 18088: 18088
Error processing index 18089: 18089
Error processing index 18090: 18090
Error processing index 18091: 18091
Error processing index 18092: 18092
Error processing index 18093: 18093
Error processing index 18094: 18094
Error processing index 18095: 18095
Error processing index 18096: 18096
Error processing index 18097: 18097
Error processing index 18098: 18098
Error processing index 18099: 18099
Error processing index 18100: 18100
Error processing index 18101: 18101
Error processing index 18102: 18102
Error processing index 18103: 18103
Error processing index 18104: 18104
Error processing index 18105: 18105
Error processing index 18106: 18106
Error processing index 18107: 18107
Error processing index 18108: 18108
Error processing index 18109: 18109
Error processing index 18110: 18110
Error processing index 18111: 18111
Error processing index 18112: 18112
Error processing index 18113: 18113
Error processing index 18114: 18114
Error processing index 18115: 18115
Error processing index 18116: 18116
Error processing index 18117: 18117
Error processing index 18118: 18118
Error processing index 18119: 18119
Error processing index 18120: 18120
Error processing index 18121: 18121
Error processing index 18122: 18122
Error processing index 18123: 18123
Error processing index 18124: 18124
Error processing index 18125: 18125
Error processing index 18126: 18126
Error processing index 18127: 18127
Error processing index 18128: 18128
Error processing index 18129: 18129
Error processing index 18130: 18130
Error processing index 18131: 18131
Error processing index 18132: 18132
Error processing index 18133: 18133
Error processing index 18134: 18134
Error processing index 18135: 18135
Error processing index 18136: 18136
Error processing index 18137: 18137
Error processing index 18138: 18138
Error processing index 18139: 18139
Error processing index 18140: 18140
Error processing index 18141: 18141
Error processing index 18142: 18142
Error processing index 18143: 18143
Error processing index 18144: 18144
Error processing index 18145: 18145
Error processing index 18146: 18146
Error processing index 18147: 18147
Error processing index 18148: 18148
Error processing index 18149: 18149
Error processing index 18150: 18150
Error processing index 18151: 18151
Error processing index 18152: 18152
Error processing index 18153: 18153
Error processing index 18154: 18154
Error processing index 18155: 18155
Error processing index 18156: 18156
Error processing index 18157: 18157
Error processing index 18158: 18158
Error processing index 18159: 18159
Error processing index 18160: 18160
Error processing index 18161: 18161
Error processing index 18162: 18162
Error processing index 18163: 18163
Error processing index 18164: 18164
Error processing index 18165: 18165
Error processing index 18166: 18166
Error processing index 18167: 18167
Error processing index 18168: 18168
Error processing index 18169: 18169
Error processing index 18170: 18170
Error processing index 18171: 18171
Error processing index 18172: 18172
Error processing index 18173: 18173
Error processing index 18174: 18174
Error processing index 18175: 18175
Error processing index 18176: 18176
Error processing index 18177: 18177
Error processing index 18178: 18178
Error processing index 18179: 18179
Error processing index 18180: 18180
Error processing index 18181: 18181
Error processing index 18182: 18182
Error processing index 18183: 18183
Error processing index 18184: 18184
Error processing index 18185: 18185
Error processing index 18186: 18186
Error processing index 18187: 18187
Error processing index 18188: 18188
Error processing index 18189: 18189
Error processing index 18190: 18190
Error processing index 18191: 18191
Error processing index 18192: 18192
Error processing index 18193: 18193
Error processing index 18194: 18194
Error processing index 18195: 18195
Error processing index 18196: 18196
Error processing index 18197: 18197
Error processing index 18198: 18198
Error processing index 18199: 18199
Error processing index 18200: 18200
Error processing index 18201: 18201
Error processing index 18202: 18202
Error processing index 18203: 18203
Error processing index 18204: 18204
Error processing index 18205: 18205
Error processing index 18206: 18206
Error processing index 18207: 18207
Error processing index 18208: 18208
Error processing index 18209: 18209
Error processing index 18210: 18210
Error processing index 18211: 18211
Error processing index 18212: 18212
Error processing index 18213: 18213
Error processing index 18214: 18214
Error processing index 18215: 18215
Error processing index 18216: 18216
Error processing index 18217: 18217
Error processing index 18218: 18218
Error processing index 18219: 18219
Error processing index 18220: 18220
Error processing index 18221: 18221
Error processing index 18222: 18222
Error processing index 18223: 18223
Error processing index 18224: 18224
Error processing index 18225: 18225
Error processing index 18226: 18226
Error processing index 18227: 18227
Error processing index 18228: 18228
Error processing index 18229: 18229
Error processing index 18230: 18230
Error processing index 18231: 18231
Error processing index 18232: 18232
Error processing index 18233: 18233
Error processing index 18234: 18234
Error processing index 18235: 18235
Error processing index 18236: 18236
Error processing index 18237: 18237
Error processing index 18238: 18238
Error processing index 18239: 18239
Error processing index 18240: 18240
Error processing index 18241: 18241
Error processing index 18242: 18242
Error processing index 18243: 18243
Error processing index 18244: 18244
Error processing index 18245: 18245
Error processing index 18246: 18246
Error processing index 18247: 18247
Error processing index 18248: 18248
Error processing index 18249: 18249
Error processing index 18250: 18250
Error processing index 18251: 18251
Error processing index 18252: 18252
Error processing index 18253: 18253

In [ ]:
df3.to_csv('/content/drive/MyDrive/lavoro/Ricerca/CHI/df1csv.csv', index=False)

In [ ]:
import pandas as pd

# Supponiamo che df3 esista già
df3["Answer_LLM_prompt2"] = None  # Oppure un valore predefinito

In [ ]:
df3

,context,question,Answer_medico,Answer_LLM,Answer_LLM_PALMYRA,Answer_LLM_PALMYRA_prompt2
0,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,LCMV infections can occur after exposure to fr...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Individuals who are at risk for Lymphocytic Ch...,None
1,symptoms,What are the symptoms of Lymphocytic Choriomen...,LCMV is most commonly recognized as causing ne...,Lymphocytic Choriomeningitis (LCM) is a viral ...,Lymphocytic Choriomeningitis (LCM) is a viral ...,None
2,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,Individuals of all ages who come into contact ...,Individuals at risk for Lymphocytic Choriomeni...,Individuals who are at risk for Lymphocytic Ch...,None
3,exams and tests,How to diagnose Lymphocytic Choriomeningitis (...,"During the first phase of the disease, the mos...",Lymphocytic Choriomeningitis (LCM) is typicall...,To diagnose Lymphocytic Choriomeningitis (LCM)...,None
4,treatment,What are the treatments for Lymphocytic Chorio...,"Aseptic meningitis, encephalitis, or meningoen...",Lymphocytic Choriomeningitis (LCM) is a viral ...,Lymphocytic Choriomeningitis (LCM) is a viral ...,None
...,...,...,...,...,...,...
16402,symptoms,What are the symptoms of Familial visceral myo...,What are the signs and symptoms of Familial vi...,Familial visceral myopathy with external ophth...,Familial visceral myopathy with external ophth...,None
16403,information,What is (are) Pseudopelade of Brocq ?,Pseudopelade of Brocq (PBB) is a slowly progre...,Pseudopelade of Brocq is a rare type of scarri...,"Pseudopelade of Brocq is a rare, chronic, and ...",None
16404,symptoms,What are the symptoms of Pseudopelade of Brocq ?,What are the signs and symptoms of Pseudopelad...,"Pseudopelade of Brocq is a rare, chronic, and ...","Pseudopelade of Brocq is a rare, chronic, and ...",None
16405,treatment,What are the treatments for Pseudopelade of Br...,Is there treatment or a cure for pseudopelade ...,"Pseudopelade of Brocq is a rare, chronic infla...","Pseudopelade of Brocq is a rare, chronic, and ...",None
16406,information,What is (are) Desmoplastic small round cell tu...,"Desmoplastic small round cell tumors (DSRCT), ...",Desmoplastic small round cell tumor (DSRCT) is...,Desmoplastic small round cell tumor (DSRCT) is...,None

In [ ]:
index = df3[df3['Answer_LLM_PALMYRA'] == '-'].index[0]
print(index)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
import pandas as pd

# Supponendo che df3 sia già definito
#df3['Answer_LLM_PALMYRA'] = '-'  # Aggiunge la colonna con valori iniziali 'None'

print(df3.head())  # Visualizza le prime righe del DataFrame per verifica

           context                                           question  \
0   susceptibility  Who is at risk for Lymphocytic Choriomeningiti...
1         symptoms  What are the symptoms of Lymphocytic Choriomen...
2   susceptibility  Who is at risk for Lymphocytic Choriomeningiti...
3  exams and tests  How to diagnose Lymphocytic Choriomeningitis (...
4        treatment  What are the treatments for Lymphocytic Chorio...

                                       Answer_medico  \
0  LCMV infections can occur after exposure to fr...
1  LCMV is most commonly recognized as causing ne...
2  Individuals of all ages who come into contact ...
3  During the first phase of the disease, the mos...
4  Aseptic meningitis, encephalitis, or meningoen...

                                          Answer_LLM Answer_LLM_PALMYRA
0  Lymphocytic Choriomeningitis (LCM) is a viral ...                  -
1  Lymphocytic Choriomeningitis (LCM) is a viral ...                  -
2  Individuals at risk for Lymphocytic Choriomeni...                  -
3  Lymphocytic Choriomeningitis (LCM) is typicall...                  -
4  Lymphocytic Choriomeningitis (LCM) is a viral ...                  -

In [ ]:
df3.to_csv('/content/drive/MyDrive/lavoro/Ricerca/CHI/df1csv.csv', index=False)

In [ ]:
df3.to_csv('/content/drive/MyDrive/lavoro/Ricerca/CHI/df1csv1.csv', index=False)

In [ ]:
import pandas as pd

# Supponiamo che il tuo DataFrame si chiami 'df'
df1 = df1.iloc[:3930]  # Mantieni solo le righe fino alla 2907 (indice 2906)

# Per aggiornare il DataFrame originale
df1.reset_index(drop=True, inplace=True)  # (Facoltativo) Resetta gli indici

In [ ]:
import pandas as pd

# Funzione per confrontare i DataFrame e stampare le righe non corrispondenti
def confronto_question_e_righe(df, df1):
    # Seleziona le righe di df corrispondenti agli indici di df1
    df_subset = df.loc[df1.index]

    # Confronta il campo 'question' tra df_subset e df1
    confronto = df_subset['question'] == df1['question']

    # Trova le righe che non corrispondono
    righe_non_corrispondenti = df1[~confronto]

    # Stampa il risultato
    if righe_non_corrispondenti.empty:
        print("Tutte le righe di df1 corrispondono a quelle di df nel campo 'question'.")
    else:
        print("Le seguenti righe di df1 non corrispondono a quelle di df nel campo 'question':")
        print(righe_non_corrispondenti)

# Esempio di utilizzo
confronto_question_e_righe(df, df3)

Tutte le righe di df1 corrispondono a quelle di df nel campo 'question'.

In [ ]:
import pandas as pd

# Funzione per creare df3
def crea_df3_selettivo(df, df1):
    # Crea una copia di df1
    df3 = df1.copy()

    # Identifica gli indici delle righe da aggiornare
    indici_da_sostituire = df1.index

    # Sostituisci i valori di 'question' con quelli di df
    df3.loc[indici_da_sostituire, 'question'] = df.loc[indici_da_sostituire, 'question']

    # Azzera i valori delle altre colonne solo per le righe modificate
    for col in df3.columns:
        if col != 'question':
            df3.loc[indici_da_sostituire, col] = '-'

    return df3

# Esempio di utilizzo
df3 = crea_df3_selettivo(df1, df1)
print(df3)

                                               question context answer
0     Who is at risk for Lymphocytic Choriomeningiti...       -      -
1     What are the symptoms of Lymphocytic Choriomen...       -      -
2     Who is at risk for Lymphocytic Choriomeningiti...       -      -
3     How to diagnose Lymphocytic Choriomeningitis (...       -      -
4     What are the treatments for Lymphocytic Chorio...       -      -
...                                                 ...     ...    ...
3925              How to diagnose Parkinson's Disease ?       -      -
3926                What is (are) Parkinson's Disease ?       -      -
3927  What are the treatments for Parkinson's Disease ?       -      -
3928     What are the symptoms of Parkinson's Disease ?       -      -
3929                What is (are) Parkinson's Disease ?       -      -

[3930 rows x 3 columns]

In [ ]:
import pandas as pd

# Supponiamo che df1 e df3 siano già definiti

# Confronta il campo 'question' tra df3 e df1
df3['answer'] = df3.apply(
    lambda row: '-' if row['question'] not in df1['question'].values else row['answer'],
    axis=1
)

# Visualizza il risultato
print(df3)

                                               question          context  \
0     Who is at risk for Lymphocytic Choriomeningiti...   susceptibility
1     What are the symptoms of Lymphocytic Choriomen...         symptoms
2     Who is at risk for Lymphocytic Choriomeningiti...   susceptibility
3     How to diagnose Lymphocytic Choriomeningitis (...  exams and tests
4     What are the treatments for Lymphocytic Chorio...        treatment
...                                                 ...              ...
3925              How to diagnose Parkinson's Disease ?  exams and tests
3926                What is (are) Parkinson's Disease ?      information
3927                What is (are) Parkinson's Disease ?        treatment
3928  What are the treatments for Parkinson's Disease ?         symptoms
3929     What are the symptoms of Parkinson's Disease ?      information

                                                 answer
0     Lymphocytic Choriomeningitis (LCM) is a viral ...
1     Lymphocytic Choriomeningitis (LCM) is a viral ...
2     Lymphocytic Choriomeningitis (LCM) is a viral ...
3     To diagnose Lymphocytic Choriomeningitis (LCM)...
4     Lymphocytic Choriomeningitis (LCM) is a viral ...
...                                                 ...
3925  The diagnosis of Parkinson's Disease involves ...
3926  Parkinson's Disease is a progressive neurologi...
3927  Parkinson's Disease is a neurodegenerative dis...
3928  Parkinson's Disease is a progressive neurologi...
3929  Parkinson's Disease is a progressive neurologi...

[3930 rows x 3 columns]

In [ ]:
df1

                                               question context answer
0     Who is at risk for Lymphocytic Choriomeningiti...       -      -
1     What are the symptoms of Lymphocytic Choriomen...       -      -
2     Who is at risk for Lymphocytic Choriomeningiti...       -      -
3     How to diagnose Lymphocytic Choriomeningitis (...       -      -
4     What are the treatments for Lymphocytic Chorio...       -      -
...                                                 ...     ...    ...
3925              How to diagnose Parkinson's Disease ?       -      -
3926                What is (are) Parkinson's Disease ?       -      -
3927  What are the treatments for Parkinson's Disease ?       -      -
3928     What are the symptoms of Parkinson's Disease ?       -      -
3929                What is (are) Parkinson's Disease ?       -      -

[3930 rows x 3 columns]

In [ ]:
from openai import OpenAI
import pandas as pd

def update_dataframe(query, Risposta, row_index):
    """
    Aggiorna il DataFrame `df3` alla riga specificata con la risposta fornita.
    """
    global df3  # Assicurati che il DataFrame `df3` esista nello scope globale
    answer = Risposta.strip()  # La risposta diventa il contenuto aggiornato della colonna `answer`
    df3.at[row_index, 'answer'] = answer  # Aggiorna la riga specificata con la risposta

# Configurazione del client OpenAI
client = OpenAI(
    base_url="https://integrate.api.nvidia.com/v1",
    api_key=""
)

# Itera solo sulle righe di `df3` che hanno un '-' nella colonna `answer`
rows_with_dash = df3[df3['answer'] == '-'].index  # Ottieni gli indici delle righe con '-'

for index in rows_with_dash:
    query = df3.loc[index, 'question']  # Prendi la query dalla colonna `question`

    # Costruisci il template del prompt
    prompt_template = f'''[INST] <<SYS>>

    You are a helpful, respectful, and honest Doctor. Always answer as helpfully as possible using the context text provided.

    Answer describing in a scientific way. Be formal during the answer. Use the third person.

    Answer like a doctor who is answering on an online forum or who is speaking with a patient.

    Don't make a list. Answer in a discursive way.

    Don't enumerate. Answer being polite and caring.

    Don't use structures like "in summary" or "following" or "In addition."

    <<SYS>>

    Question: {query} [/INST]
    '''
    try:
        # Chiamata API per generare la risposta
        completion = client.chat.completions.create(
            model="mistralai/mixtral-8x22b-instruct-v0.1",
            messages=[{"role": "user", "content": prompt_template}],
            temperature=0.5,
            top_p=1,
            max_tokens=1024,
            stream=True
        )

        # Raccogli la risposta generata
        Risposta = ""
        for chunk in completion:
            if chunk.choices[0].delta.content:
                Risposta += chunk.choices[0].delta.content

        # Debugging: Stampa la risposta per verificare
        print(f"Response for index {index}: {Risposta}")

        # Aggiorna il DataFrame `df3` con la risposta generata
        update_dataframe(query, Risposta, index)

    except Exception as e:
        print(f"Error during API call for index {index}: {e}")

Response for index 855: Gerstmann-Straussler-Scheinker Disease (GSS) is a rare, inherited prion disease that affects the central nervous system. Unfortunately, there is currently no cure for GSS, and treatment is primarily focused on managing symptoms and providing supportive care.

One of the main treatments for GSS is the use of medications to manage symptoms such as seizures, muscle stiffness, and difficulty with coordination. Anticonvulsants may be used to control seizures, while muscle relaxants may be prescribed to help with muscle stiffness and spasms. Physical therapy may also be recommended to help maintain mobility and prevent muscle contractures.

In addition to symptom management, supportive care is an important aspect of treatment for GSS. This can include providing assistance with activities of daily living, such as eating and bathing, as well as providing emotional support to patients and their families. Genetic counseling may also be recommended for individuals with a family history of the disease.

Research is ongoing to develop new treatments for GSS, including potential therapies that target the underlying cause of the disease. However, at present, treatment options are limited and the focus is on managing symptoms and providing supportive care to improve quality of life for individuals with GSS.
Response for index 856: The outlook for Gerstmann-Straussler-Scheinker Disease (GSS) is unfortunately quite grim, as it is a rare, inherited, and fatal neurodegenerative disorder. GSS is characterized by the accumulation of an abnormal form of the prion protein in the brain, leading to progressive neurological symptoms such as ataxia, dementia, and visual disturbances.

The disease typically begins in mid-adulthood and progresses slowly over several years, leading to severe disability and ultimately death. There is currently no cure or effective treatment for GSS, and management is focused on symptom relief and supportive care.

Research is ongoing to better understand the underlying mechanisms of the disease and to develop potential therapies, but progress has been slow due to the rarity of the condition and the complexity of prion diseases. It is important for individuals with a family history of GSS to undergo genetic testing and counseling to assess their risk and to make informed decisions about family planning and medical care.
Response for index 858: Syringomyelia is a medical condition characterized by the formation of fluid-filled cavities, or syrinxes, within the spinal cord. These cavities can cause damage to the spinal cord and its surrounding nerves, leading to a range of symptoms such as pain, weakness, and loss of sensation. The condition is often associated with other disorders such as Chiari malformation, which is a structural abnormality of the brain. Treatment options for syringomyelia depend on the severity of the condition and may include medications, physical therapy, and surgery. It is important for individuals with syringomyelia to work closely with their healthcare provider to develop a personalized treatment plan.
Response for index 860: The outlook for Syringomyelia, a condition characterized by the formation of fluid-filled cysts within the spinal cord, can vary greatly depending on the severity and progression of the condition. In some cases, the condition may remain stable for many years, while in others, it may progress more rapidly.

The primary goal of treatment for Syringomyelia is to alleviate symptoms and prevent further progression of the condition. This may involve a combination of medical management, such as pain management and physical therapy, and surgical intervention, such as procedures to drain or remove the cysts.

The success of treatment depends on a variety of factors, including the underlying cause of the condition, the size and location of the cysts, and the severity of symptoms. In some cases, treatment may be able to effectively manage symptoms and prevent further progression of the condition, while in others, the condition may continue to progress despite treatment.

It is important for individuals with Syringomyelia to work closely with their healthcare team to develop an individualized treatment plan that takes into account their specific needs and circumstances. Regular monitoring and follow-up care are also important to ensure that the condition is being effectively managed and to detect any signs of progression or complications.

In summary, the outlook for Syringomyelia can vary depending on a variety of factors, and individuals with this condition should work closely with their healthcare team to develop an individualized treatment plan and monitor their condition over time.
Response for index 861: Syringomyelia is a condition characterized by the presence of a fluid-filled cavity or cyst (syrinx) within the spinal cord. This condition can lead to a variety of symptoms, including pain, weakness, and loss of sensation.

Research into Syringomyelia is ongoing and multifaceted, with a focus on understanding the underlying causes and developing effective treatments. Some of the current areas of research include:

1. Pathophysiology: Researchers are investigating the mechanisms by which syringomyelia develops and progresses. This includes studying the role of genetic factors, inflammation, and other biological processes.
2. Imaging: Advances in imaging technology, such as magnetic resonance imaging (MRI), have improved the ability to diagnose and monitor syringomyelia. Researchers are exploring new imaging techniques to better understand the condition and guide treatment decisions.
3. Treatment: There is currently no cure for syringomyelia, and treatment is focused on managing symptoms and preventing progression. Researchers are investigating new surgical techniques, medications, and other interventions to improve outcomes for patients.
4. Epidemiology: Researchers are studying the incidence and prevalence of syringomyelia, as well as risk factors and potential preventive measures.
5. Quality of life: Researchers are also investigating the impact of syringomyelia on patients' quality of life, and exploring interventions to improve functional outcomes and overall well-being.

Overall, the goal of research into Syringomyelia is to improve our understanding of the condition, develop effective treatments, and ultimately improve the lives of patients affected by this condition.
Response for index 862: Dandy-Walker Syndrome is a congenital brain malformation that affects the development of the cerebellum, the part of the brain responsible for coordinating movement and balance. It is characterized by the presence of a cyst in the fourth ventricle, a fluid-filled space in the brain, as well as an enlarged posterior fossa, the space at the back of the brain. This syndrome can lead to a range of neurological symptoms, including developmental delays, motor impairments, and intellectual disabilities. The severity of symptoms can vary widely among individuals, and the syndrome is often associated with other brain abnormalities. Treatment typically involves managing symptoms and addressing any associated conditions, and may include physical therapy, occupational therapy, and medications.
Response for index 865: The field of medical research is constantly evolving, and there are ongoing studies and clinical trials for many conditions, including Dandy-Walker Syndrome. Dandy-Walker Syndrome is a rare genetic condition characterized by abnormalities in the structure of the brain, particularly the cerebellum and the fluid-filled spaces around it.

Several research studies are being conducted to better understand the genetic basis of Dandy-Walker Syndrome and to identify potential therapeutic targets. For instance, a study published in the Journal of Neurosurgery Pediatrics in 2020 investigated the use of a medication called Eteplirsen in treating Dandy-Walker Syndrome. The study found that Eteplirsen may improve motor function and cognitive abilities in individuals with the condition.

Another area of research focuses on developing new imaging techniques to improve the diagnosis and monitoring of Dandy-Walker Syndrome. A study published in the Journal of Neuroimaging in 2019 explored the use of a novel MRI technique called susceptibility-weighted imaging (SWI) in identifying abnormalities in the brains of individuals with Dandy-Walker Syndrome. The study found that SWI may be a useful tool for diagnosing and monitoring the condition.

In addition to these studies, there are ongoing clinical trials investigating the use of various therapies for Dandy-Walker Syndrome, including physical therapy, occupational therapy, and speech therapy. These therapies aim to improve the functional abilities of individuals with the condition and enhance their quality of life.

Overall, the research on Dandy-Walker Syndrome is ongoing, and there is much to learn about this complex condition. However, the existing studies and clinical trials offer hope for the development of new and improved treatments for individuals with Dandy-Walker Syndrome. As always, it is important for individuals with the condition to work closely with their healthcare providers to develop a comprehensive treatment plan that meets their unique needs and goals.
Response for index 867: Spina Bifida is a neural tube defect that occurs during the early stages of fetal development, leading to an incomplete closure of the spinal column. The severity of the condition can vary, and the treatments are tailored accordingly.

In mild cases, where there is no protrusion of the spinal cord, no treatment may be required. However, regular monitoring is essential to ensure no further complications arise.

In more severe cases, where there is a protrusion of the spinal cord or meninges, surgery is often recommended. This can involve closing the opening in the spine and protecting the spinal cord. The surgery is typically performed soon after birth to minimize further damage.

Following surgery, ongoing care is necessary to manage potential complications. This can include physical therapy to improve mobility, as well as regular monitoring for conditions such as hydrocephalus, which is a buildup of fluid in the brain.

In addition to surgery, other treatments may be recommended depending on the individual's symptoms and needs. These can include medications to manage pain or muscle spasticity, as well as assistive devices such as braces or wheelchairs to improve mobility.

It is important to note that while these treatments can help manage the symptoms of Spina Bifida, there is currently no cure for the condition. However, with appropriate care and management, individuals with Spina Bifida can lead full and active lives.

In [ ]:
df3

,context,question,Answer_medico,Answer_LLM
0,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,LCMV infections can occur after exposure to fr...,-
1,symptoms,What are the symptoms of Lymphocytic Choriomen...,LCMV is most commonly recognized as causing ne...,-
2,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,Individuals of all ages who come into contact ...,-
3,exams and tests,How to diagnose Lymphocytic Choriomeningitis (...,"During the first phase of the disease, the mos...",-
4,treatment,What are the treatments for Lymphocytic Chorio...,"Aseptic meningitis, encephalitis, or meningoen...",-
...,...,...,...,...
16402,symptoms,What are the symptoms of Familial visceral myo...,What are the signs and symptoms of Familial vi...,-
16403,information,What is (are) Pseudopelade of Brocq ?,Pseudopelade of Brocq (PBB) is a slowly progre...,-
16404,symptoms,What are the symptoms of Pseudopelade of Brocq ?,What are the signs and symptoms of Pseudopelad...,-
16405,treatment,What are the treatments for Pseudopelade of Br...,Is there treatment or a cure for pseudopelade ...,-
16406,information,What is (are) Desmoplastic small round cell tu...,"Desmoplastic small round cell tumors (DSRCT), ...",-

In [ ]:
df3

,context,question,Answer_medico,Answer_LLM
0,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,LCMV infections can occur after exposure to fr...,-
1,symptoms,What are the symptoms of Lymphocytic Choriomen...,LCMV is most commonly recognized as causing ne...,-
2,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,Individuals of all ages who come into contact ...,-
3,exams and tests,How to diagnose Lymphocytic Choriomeningitis (...,"During the first phase of the disease, the mos...",-
4,treatment,What are the treatments for Lymphocytic Chorio...,"Aseptic meningitis, encephalitis, or meningoen...",-
...,...,...,...,...
16402,symptoms,What are the symptoms of Familial visceral myo...,What are the signs and symptoms of Familial vi...,-
16403,information,What is (are) Pseudopelade of Brocq ?,Pseudopelade of Brocq (PBB) is a slowly progre...,-
16404,symptoms,What are the symptoms of Pseudopelade of Brocq ?,What are the signs and symptoms of Pseudopelad...,-
16405,treatment,What are the treatments for Pseudopelade of Br...,Is there treatment or a cure for pseudopelade ...,-
16406,information,What is (are) Desmoplastic small round cell tu...,"Desmoplastic small round cell tumors (DSRCT), ...",-